var GAME_LEVELS = [
["            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
 "            x                                                                                                         x  ",
 "            x                                                                                                         x  ",
 "            x                              x o  o  x                                                                  x  ",
 "            x                   yyyyyyyyy  x   x   x  yyyyyy x s x  yyyyyy x   x  yyyyyy                              x  ",
 "            x                   y   y   y  x   x   x  y    y xxxxx  y    y xxxxx  y    y xx                           x  ",
 "            x                   y   y   y  xxxxxxxxx  yyyyyy x   x  yyyyyy x   x  yyyyyy                              x  ",
 "            x                   y       y             y    y        y    y        y    y                              x  ",
 "            x                       o o                                                                         y  o  x  ",
 "            x                                                                                              xxx  yyyyyyy  ",
 "            x                                                                  o                           x             ",
 "            x                                       x           x              o   b                      x              ",
 "            x                           o o      xx!! x||!!!xx!!    xx   o    yyy                        x               ",
 "            x          o   o                xxxx                       x                               x                 ",
 " xxxx       x              x         xxxx     !!!                        x                          x                    ",
 " x  xxxxxxxxx        xxxx       xxxx    !!!                               ! x !   ooo        xxx  x                      ",
 " x @                                !!                       !!!!               xxxxxxxx   xx   xx                       ",
 " xxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxx                                                                                       ",
 "               x!!!!x                                                 !!!!                    s                          ",
 "               x!!!!x                                                                      xxxxxxxxx !o!                 ",
 "               xxxxxx                                                                                !y!                 ",
 "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!||!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
 "                                                                                        x!!x                             ",
 "                                                                                        xxxx                             "],

  ["                                                                                                                                                ",
  "                                                                                                                                                 ",
  "                                                                                                                                                 ",
  "                                                                                                                                                 ",
  "                                                                                                                                                 ",
  "                                                                                                                                                 ",
  "                                                                                      b                                                   s      ",
  "                                                                            xxxxxxxxxxxxxxxxxxxxxx         xx xxx     xx   x   x        xxxxxx   ",
  "                                                                                                                                                 ",
  "                                     ===                               x                                                                         ",
  "                                                                   x                                                                             ",
  "   ==                                                            x                                                                               ",
  "                           ==              ==                  x                                                                                 ",
  "                                                           x                                                                                     ",
  "                                            v             x                                                                                      ",
  "                                                     x!!!!                                                                                       ",
  "                                                   x                                                                                             ",
  "                  xxx   yyyyyyyyy   vv           x                                                                                               ",
  "                  x!x                          x                                                                                                 ",
  "                  x!x                        x  |                                                                                                ",
  "                  xvx                     xxx                                                                                                    ",
  "                                                                                                                                                 ",
  "                                       xx                                                                                                        ",
  "                                 xxx                                                                                                             ",
  "                     xxxx           ||                                                                                                           ",
  "                 xx      x|x x|x                                                                                                                 ",
  "      @    xxx           x!x x!x                                                                   s      o     s                                ",
  "    xxxxxxx    |         x!x x!x                                                                   xxxxxxxxxxxxxx                                ",
  "                         xxx xxx                                                                                                                 ",
  "                                                                                                                                                "],



  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
  " |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||  ",
  " yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy  ",
  "                                                                                                                                                                                      ",
  "                                                                                                                                                                                      ",
  "                                                                                                                                                                                      ",
  "                                                                                                                                                                                      ",
  "                      xxx                                                                                                                                                             ",
  "           @          !!!     vvvv  vv            xx x                                    b                                                                                           ",
  "           xx          v                   x          x                      s        x  xxx                                                                                    !o!   ",
  "                                         x                                  xx !!                          x                                                                  xxx   x ",
  "                           x           x                   x!!!!!!!!!!!x                                x                                                                          x  ",
  "                                                                                        x                                                                                         x   ",
  "              x|x    x                                                                 | |          x                 xx x x x x x x x x x x x x x x x x x x x x x x x x x x    !o!   ",
  "              xxx            |    |  |                                                                                    |   |   |   |   |   |   |   |   |   |   |   |   |     xxx   ",
  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! "],


  ["                                                                                                ",
  "                 x     x  xxxxxxxxx  x=   =x         x ooooooooooooo x xxxxxxxxxx xxxxxx         ",
  "                 x     x  xvvvvvvvx  x     x         x ooooooooooooo x xxxxvvxxxx xvvvvx         ",
  "                 xxxxxxx  x|||||||x  x=   =x         x      xxx      x    x  x    x    x         ",
  "                   x!x    xxxxxxxxx  xxxxxxx         x      x x      x    x  x    x    x         ",
  "                   x!x                               xxxxxxxx xxxxxxxx xxxx||xxxx x    x         ",
  "                   x!x                                                 xxxxxxxxxx                ",
  "                                                                                                 ",
  "                                                                                                 ",
  "                                                                                                 ",
  "  @                                                                                              ",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];


if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
